FROM ubuntu:20.04
MAINTAINER switchchow switchchow@example.com
ENV REFRESHED_AT 2020-09-30
COPY sources.list /etc/apt/sources.list

USER root
RUN apt-get -qq update && apt-get -qq install sudo curl gnupg2 apt-transport-https ca-certificates curl gnupg-agent software-properties-common
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers


VOLUME [ "/var/lib/docker" ]

RUN mkdir -p /var/log/jenkins && chown -R jenkins:jenkins /var/log/jenkins
RUN mkdir -p /var/cache/jenkins && chown -R jenkins:jenkins /var/cache/jenkins
ENV JENKINS_OPTS="--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --prefix=/jenkins"

COPY dockerjenkins.sh /usr/local/bin/dockerjenkins.sh
RUN chmod +x /usr/local/bin/dockerjenkins.sh

USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

CMD [ "dockerjenkins.sh" ]
