FROM ubuntu:20.04
MAINTAINER switchchow switchchow@example.com
ENV REFRESHED_AT 2020-09-30

USER root
RUN apt-get update -qqy && apt-get install -qqy sudo curl gnupg2 apt-transport-https ca-certificates curl gnupg-agent software-properties-common
RUN curl -fsSL http://mirrors.aliyun.com/docker-ce/linux/ubuntu/gpg |  apt-key add -
RUN  add-apt-repository "deb [arch=amd64] http://mirrors.aliyun.com/docker-ce/linux/ubuntu $(lsb_release -cs) stable"
RUN apt-get update -qq && apt-get install -y docker-ce && apt-get install -qqy iptables ca-certificates lxc openjdk-8-jdk git-core
VOLUME [ "/var/lib/docker" ]

RUN useradd jenkins
RUN sed -s '/jenkins/d' /etc/sudoers
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers
RUN usermod -aG docker jenkins

VOLUME [ "/var/lib/docker" ]

RUN mkdir -p /var/log/jenkins && chown -R jenkins:jenkins /var/log/jenkins
RUN mkdir -p /var/cache/jenkins && chown -R jenkins:jenkins /var/cache/jenkins
ENV JENKINS_OPTS="--logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --prefix=/jenkins"

COPY dockerjenkins.sh /usr/local/bin/dockerjenkins.sh
RUN chmod +x /usr/local/bin/dockerjenkins.sh

USER jenkins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

CMD [ "dockerjenkins.sh" ]
